version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  pre-build:
    commands:
      - $(aws ecr get-logiin --region $AWS_DEFAULT_REGIOON --no-include-email)
      - REPO=$(aws ecr describe-repositories --repository-names example --output text --query "repositories[0].repositryUri")
    build:
      commands:
        - docker build -t $IMAGE .
        - docker push $IMAGE
    post_build:
      commands:
        - printf '[{"name": "example", "imageUri": "%s"}]' $IMAGE > imagedefinitions.json
  artigacts:
    files: imagedefinitions.json